# two stages to be added qemu, kernel
stages:
    - laputa_test

laputa_test:
    stage: laputa_test
    script:
        - git submodule update --init --recursive
        - ./scripts/local/build_qemu.sh
        - ./scripts/local/build_linux.sh
        - ./scripts/local/build_opensbi.sh
        - ./scripts/local/copy_laputa_to_vm.sh
        - ./scripts/expect_wrapper.sh ./scripts/local/laputa_test.exp
    only:
        - merge_requests
        - schedules
