# two stages to be added qemu, kernel
stages:
    - laputa_test

ulh_test:
    stage: laputa_test
    script:
        - ./scripts/copy_laputa_to_vm.sh
        - ./scripts/expect_wrapper.sh ./scripts/laputa_test.exp
    only:
        - merge_requests
