# two stages to be added qemu, kernel
stages:
    - ulh_test

ulh_test:
    stage: ulh_test
    script:
        - ./scripts/copy_ulh_to_vm.sh
        - ./scripts/expect_wrapper.sh ./scripts/ulh_test.exp
    only:
        - merge_requests
