# two stages to be added qemu, kernel
stages:
    - laputa_test

laputa_test:
    stage: laputa_test
    script:
        - git submodule update --init --recursive
        - ./scripts/local/build_qemu.sh
        - ./scripts/local/build_linux.sh
        - ./scripts/local/build_opensbi.sh
        - ./scripts/local/docker_build_laputa.sh debug
        - ./scripts/local/docker_build_laputa.sh
        - ./scripts/expect_wrapper.sh ./scripts/local/laputa_test_standalone.exp
        - sleep 5
        - ./scripts/local/laputa_test_network.sh
        - ./scripts/local/laputa_test.sh
    after_script:
        - sudo rm -r mnt
        - sudo rm -r target
        - sudo rm -r tests/integration/test_images/build
    only:
        - merge_requests
        - schedules
