#!/usr/bin/expect -f
source [file join [file dirname $argv0] ./laputa_test_main_multi_vm_smp.tcl]

set timeout 180
set env(TERM) xterm-256color
set env(SHELL) /bin/bash
set env(HOME) /home/gitlab-runner
set env(PATH) /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
set env(LOGNAME) gitlab-runner
set env(SHLVL) 2
set env(MAIL) /var/mail/gitlab-runner
set env(SUDO_UID) 1000
set env(SUDO_GID) 1000
set env(SUDO_COMMAND) /bin/bash

spawn bash -c "killall qemu-system-riscv64"

sleep 10

# Start 8 VMs
spawn bash -c "screen -r virt"

send "./scripts/local/boot.sh \n"

main_test_multi_vm_2_8

sleep 100

send "\x01"; send "d"

# Start the VMs by ssh
# Let VM-0 run workload
spawn bash  -c "screen -r host-0"

main_test_multi_vm_host_ip_7_start

send "\x01"; send "d"

# Let VM-1 run workload
spawn bash  -c "screen -r host-1"

main_test_multi_vm_host_ip_8_start

send "\x01"; send "d"

# Let VM-2 run workload
spawn bash  -c "screen -r host-2"

main_test_multi_vm_host_ip_9_start

send "\x01"; send "d"

# Let VM-3 run workload
spawn bash  -c "screen -r host-3"

main_test_multi_vm_host_ip_10_start

send "\x01"; send "d"

# Let VM-4 run workload
spawn bash  -c "screen -r host-4"

main_test_multi_vm_host_ip_11_start

send "\x01"; send "d"

# Let VM-5 run workload
spawn bash  -c "screen -r host-5"

main_test_multi_vm_host_ip_12_start

send "\x01"; send "d"

# Let VM-6 run workload
spawn bash  -c "screen -r host-6"

main_test_multi_vm_host_ip_13_start

send "\x01"; send "d"

# Let VM-7 run workload
spawn bash  -c "screen -r host-7"

main_test_multi_vm_host_ip_14_start

send "\x01"; send "d"

# Check the VMs
# Check VM-0
spawn bash  -c "screen -r host-0"

main_test_multi_vm_host_ip_7_check

send "\x01"; send "d"

# Check VM-1
spawn bash  -c "screen -r host-1"

main_test_multi_vm_host_ip_8_check

send "\x01"; send "d"

# Check VM-2
spawn bash  -c "screen -r host-2"

main_test_multi_vm_host_ip_9_check

send "\x01"; send "d"

# Check VM-3
spawn bash  -c "screen -r host-3"

main_test_multi_vm_host_ip_10_check

send "\x01"; send "d"

# Check VM-4
spawn bash  -c "screen -r host-4"

main_test_multi_vm_host_ip_11_check

send "\x01"; send "d"

# Check VM-5
spawn bash  -c "screen -r host-5"

main_test_multi_vm_host_ip_12_check

send "\x01"; send "d"

# Check VM-6
spawn bash  -c "screen -r host-6"

main_test_multi_vm_host_ip_13_check

send "\x01"; send "d"

# Check VM-7
spawn bash  -c "screen -r host-7"

main_test_multi_vm_host_ip_14_check

send "\x01"; send "d"

#main_test_multi_vm_host_2_8

puts "Test OK"
