#!/usr/bin/expect -f

set timeout 180

spawn bash -c "ssh -p 2333 ubuntu@localhost"

expect {
    "ubuntu@ubuntu:" {
        send "sudo mount /dev/vdb /mnt &&
        cd /mnt/linux-laputa    &&
        sudo make modules_install   &&
        sudo make install   &&
        sudo grub-mkconfig -o /boot/grub/grub.cfg &&
        sudo rm /boot/*.old &&
        sudo reboot\n"

        exp_continue
    }
        
    eof {

    }
}
