#!/usr/bin/expect -f

set timeout 180
set env(TERM) xterm-256color
set env(SHELL) /bin/bash
set env(HOME) /home/gitlab-runner
set env(PATH) /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
set env(LOGNAME) gitlab-runner
set env(SHLVL) 2
set env(MAIL) /var/mail/gitlab-runner
set env(SUDO_UID) 1000
set env(SUDO_GID) 1000
set env(SUDO_COMMAND) /bin/bash

# set args_for_laputa_test [lindex $argv 0];

spawn bash -c "killall qemu-system-riscv64"

spawn bash -c "./scripts/local/boot.sh"

expect {
    "Please press Enter to activate this console" {
        send "\n ./chroot.sh \n
        mount -t proc proc /proc \n
        mount -t sysfs sysfs /sys \n
        mount -t devtmpfs devtmpfs /dev \n"
  #      echo 5 > /proc/sys/kernel/printk \n"
        exp_continue
    }

    "root@(none)" {
        send "cd laputa && ./run_tests.sh $argv\n"
        expect {
            "ALL TEST PASSED" {
        
            }
            timeout {
                exit -1
            }
        }
    }
    timeout {
        exit -1
    }
}

puts "Test OK"
