#!/usr/bin/expect -f
source [file join [file dirname $argv0] ./laputa_test_main.tcl]

set timeout 180

spawn bash -c "./scripts/local/boot.sh"


expect {
    "Please press Enter to activate this console" {
        send "\n  ./chroot.sh\n"
        exp_continue
    }

    "root@(none)" {
        send "cd laputa && ./run_tests.sh\n"
    }
    timeout {
        exit -1
    }
}

main_test

puts "Test OK"
