#!/usr/bin/expect -f
source [file join [file dirname $argv0] ./laputa_test_main.tcl]

set timeout 180

spawn bash -c "./scripts/local/boot.sh"


expect {
    "Please press Enter to activate this console" {
        send "\n ./chroot.sh \n
        mount -t proc proc /proc \n
        mount -t sysfs sysfs /sys \n
        mount -t devtmpfs devtmpfs /dev \n 
        ./laputa/ioctl_test\n"
        exp_continue
    }

    "tests passed" {

    }
    
    timeout {
        exit -1
    }
}

puts "Test OK"
