#!/usr/bin/expect -f

proc do_console_login { login pass } {
    set login_helper 4

    expect {
        "Enter choice:" { 
            send "1\n" 
            exp_continue
        }
        "login:" {
            set login_helper [expr {$login_helper - 1}]
            if {$login_helper == 0} {
                send "$login\n"
            } else {
                send "\n"
            }
            exp_continue
        }
        "Password:" { 
            send "$pass\n" 
            exp_continue
        }
        "ubuntu@ubuntu:~\\\$" {
            puts "log in successfully!!\n"
        }
        timeout {
            exit -1
        }
    }
}

source [file join [file dirname $argv0] laputa_test_main.tcl]

set timeout 180

# make sure previous operation release ubuntu image lock
sleep 5

spawn bash -c "./scripts/boot.sh"

do_console_login "ubuntu" "ipads123"

send "cd laputa && ./run_tests.sh\n"
expect {
    "test failed" {
        exit -1
    }
    "ALL TEST PASSED" {

    }
    timeout {
        exit -1
    }
}

main_test

send "\001x\n"
expect {
    eof
}

puts "Test OK"
