#!/usr/bin/expect -f

proc do_console_login { login pass } {
    set login_helper 4

    expect {
        "Enter choice:" { 
            send "1\n" 
            exp_continue
        }
        "login:" {
            set login_helper [expr {$login_helper - 1}]
            if {$login_helper == 0} {
                send "$login\n"
            } else {
                send "\n"
            }
            exp_continue
        }
        "Password:" { 
            send "$pass\n" 
            exp_continue
        }
        "ubuntu@ubuntu:~\\\$" {
            puts "log in successfully!!\n"
        }
        timeout {
            exit -1
        }
    }
}
set timeout 180

# make sure previous operation release ubuntu image lock
sleep 5

spawn bash -c "./scripts/boot.sh"

do_console_login "ubuntu" "ipads123"

# Run unit tests and integration tests
send "cd laputa && ./run_tests.sh\n"
expect {
    "test failed" {
        exit -1
    }
    "ALL TEST PASSED" {

    }
    timeout {
        exit -1
    }
}

# Test the binary
expect "ubuntu@ubuntu:~/laputa\\\$"

send "./laputa --smp 4\n"
expect {
    "Error: please provide memory size by using --memory or config files." {
        
    }
    timeout {
        -1
    }
}

send "./laputa --memory 128\n"
expect {
    "Error: please provide vcpu count by using --smp or config files." {
        
    }
    timeout {
        -1
    }
}

send "./laputa --smp 4 --memory 128\n"
expect {
    "Error: please provide kernel image by using --kernel or config files." {
        
    }
    timeout {
        -1
    }
}

send "\001x\n"
expect {
    eof
}

puts "Test OK"
