name: Laputa
version: "1.0"
author: Jiahao Chen, Dingji Li, Yuxuan Liu, Zeyu Mi
about: A user-level hypervisor written in Rust for RISC-V
args:
    - vm_config:
        long: config
        value_name: CONFIG
        help: Sets the path of a configuration file for this virtual machine, its contents will overwrite all other arguments
    - machine:
        long: machine
        value_name: MACHINE
        help: Sets the machine type of this virtual machine
    - smp:
        long: smp
        value_name: SMP
        help: Sets the number of virtual CPUs
    - memory:
        long: memory
        value_name: MEMORY
        help: Sets the memory size of this virtual machine (in MegaBytes)
    - kernel:
        long: kernel
        value_name: KERNEL_IMAGE_PATH
        help: Sets the path of a kernel image file
    - dtb:
        long: dtb
        value_name: DTB
        help: Sets the path of a dtb file
    - initrd:
        long: initrd
        value_name: INITRD
        help: Sets the path of an initrd file

